INSERT INTO AIRLINES_INFANT_PRICES VALUES (NULL,'IB',10);
INSERT INTO AIRLINES_INFANT_PRICES VALUES (NULL,'BA',15);
INSERT INTO AIRLINES_INFANT_PRICES VALUES (NULL,'LH',7);
INSERT INTO AIRLINES_INFANT_PRICES VALUES (NULL,'FR',20);
INSERT INTO AIRLINES_INFANT_PRICES VALUES (NULL,'VY',10);
INSERT INTO AIRLINES_INFANT_PRICES VALUES (NULL,'TK',5);
INSERT INTO AIRLINES_INFANT_PRICES VALUES (NULL,'U2',19.90);
